language: go

branches:
  except:
    - /^wip-.*$/

os:
  - linux
  - osx
  - windows

go:
  - 1.11.x
  - 1.12rc1

before_install:
  - go get -v golang.org/x/tools/cmd/goimports

script:
  - test -z "$(goimports -d .)"
  - go test -race
