language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.11.x

before_install:
  - go get -v golang.org/x/tools/cmd/goimports

script:
  - which goimports
  - which goimports.exe
  - test -z "$(goimports -l .)"
  - test -z "$(goimports.exe -l .)"
  - go test -race
